name: ceres-deploy

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+-rc'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm build
    
  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Copy file via scp
      uses: appleboy/scp-action@master

      env:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVET_PW }}
      with:
        source: "."
        target: "/var/www/html/ceres-web"
          
