name: ceres-deploy

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      
      with:
        source: "build/*"
        target: "/var/www/html/ceres-web"
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PW }}
          
